### ISSUE TITLE
使用最新代码的 nameSrv 配置，仍然无法正常使用公网区域消息队列实例

### ISSUE THREAD

**Issue by zhb127** [ali-sdk/ali-ons#62]
继 #60 问题回复之后，更新最新代码，使用`公网`区域下的实例（仅有 TCP 协议接入点），仍然出现错误。

```node
$ node producer.js

{ MQClientException
    at MQClient._defaultHandler (/Users/bocai/study/npm/ali-ons/lib/mq_client_api.js:559:17)
    at MQClient.getTopicRouteInfoFromNameServer (/Users/bocai/study/npm/ali-ons/lib/mq_client_api.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3 name: 'MQClientException', code: undefined }
```

**Comment by zhb127** [comment]
补充 consumer.js 执行错误日志：

```node
$ node consumer.js

{ MQClientException: MQPushConsumer occurred an error [mq:client] updateAllTopicRouterInfo occurred error,
    at MQClient._defaultHandler (/Users/bocai/study/npm/ali-ons/lib/mq_client_api.js:559:17)
    at MQClient.getTopicRouteInfoFromNameServer (/Users/bocai/study/npm/ali-ons/lib/mq_client_api.js:197:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  name: 'MQClientException',
  code: undefined,
  message: 'MQPushConsumer occurred an error [mq:client] updateAllTopicRouterInfo occurred error, ' }
{ MQClientException: MQPushConsumer occurred an error [mq:client] updateAllTopicRouterInfo occurred error,
    at MQClient._defaultHandler (/Users/bocai/study/npm/ali-ons/lib/mq_client_api.js:559:17)
    at MQClient.getTopicRouteInfoFromNameServer (/Users/bocai/study/npm/ali-ons/lib/mq_client_api.js:197:14)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  name: 'MQClientException',
  code: undefined,
  message: 'MQPushConsumer occurred an error [mq:client] updateAllTopicRouterInfo occurred error, ' }
```

**Comment by denghongcai** [comment]
怎么配的

**Comment by zhb127** [comment]
`
'use strict';

const env = process.env;

// export ALI_SDK_ONS_ID=your-accesskey
// export ALI_SDK_ONS_SECRET=your-secretkey

module.exports = {
  accessKeyId: 'xxx',
  accessKeySecret: 'xxx',
  producerGroup: 'GID-payment-gateway',
  consumerGroup: 'GID-payment-gateway',
  topic: 'payment-gateway-notification',
  nameSrv: 'http://MQ_INST_1135474762988335_BaZZNagk.mq-internet-access.mq-internet.aliyuncs.com:80',
};`

**Comment by denghongcai** [comment]
nameSrv 不要带上 http:// 前缀

**Comment by zhb127** [comment]
ali-ons/example/config.js

```
'use strict';

const env = process.env;

// export ALI_SDK_ONS_ID=your-accesskey
// export ALI_SDK_ONS_SECRET=your-secretkey

module.exports = {
  accessKeyId: 'xxx',
  accessKeySecret: 'xxx',
  producerGroup: 'GID-test',
  consumerGroup: 'GID-test',
  topic: 'test',
  nameSrv: 'MQ_INST_1135474762988335_BaZZNagk.mq-internet-access.mq-internet.aliyuncs.com:80'
};
```

```
node consumer.js

{ TcpConnectionTimeoutError: MQPushConsumer occurred an error [TCPBase] socket connect timeout (3000ms) (address: 100.100.33.97:8080)
    at Socket.socket.setTimeout (/Users/bocai/study/npm/ali-ons/node_modules/tcp-base/lib/base.js:404:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  name: 'TcpConnectionTimeoutError',
  host: '100.100.33.97',
  port: '8080' }
{ TcpConnectionTimeoutError: MQPushConsumer occurred an error [TCPBase] socket connect timeout (3000ms) (address: 100.100.18.95:8080)
    at Socket.socket.setTimeout (/Users/bocai/study/npm/ali-ons/node_modules/tcp-base/lib/base.js:404:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  name: 'TcpConnectionTimeoutError',
  host: '100.100.18.95',
  port: '8080' }
```

```
git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   example/config.js

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.vscode/
	package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by denghongcai** [comment]
100.100.33.97

这个应该是内网地址，咨询下阿里云工单看看

**Comment by zhb127** [comment]
咨询了阿里云服务支持，回复：

这个是基于开源的  RocketMQ 的，和阿里云 RocketMQ 有些不同。阿里云提供了 java、C++ 和.NET的接入方式，还没有nodejs的SDK的。

**Comment by denghongcai** [comment]
这个问题是 nameSrv 给出的 broker 地址是阿里云内网的 IP，而不是 “公网IP”，是网络不通。你可以开一台 ECS 试下。ali-ons 本身就是基于开源 RocketMQ 来开发的。

**Comment by gxcsoccer** [comment]
阿里云控制台上面有接入代码示例，贴出来看看

**Comment by zhb127** [comment]
> 阿里云控制台上面有接入代码示例，贴出来看看

```java
// 推荐接入点设置方式
properties.put(PropertyKeyConst.NAMESRV_ADDR, "http://MQ_INST_125036_BaXaRFt4.mq-internet-access.mq-internet.aliyuncs.com:80");
```

**Comment by gxcsoccer** [comment]
加一个 namespace 试试

```js
module.exports = {
  accessKeyId: 'xxx',
  accessKeySecret: 'xxx',
  producerGroup: 'GID-test',
  consumerGroup: 'GID-test',
  topic: 'test',
  namespace: 'MQ_INST_1135474762988335_BaZZNagk',
  nameSrv: 'http://MQ_INST_1135474762988335_BaZZNagk.mq-internet-access.mq-internet.aliyuncs.com:80',
};
```

**Comment by gxcsoccer** [comment]
@zhb127 是否还有问题？

**Comment by zhb127** [comment]
最后提供一下环境截图
![image](https://user-images.githubusercontent.com/5210208/56550815-42779880-65b9-11e9-8119-afb841d7e310.png)
感觉接入一直失败，如果只能使用阿里云内网调试的话，对本地开发测试不利。目前，最新代码在本地开发环境下，依然报错。放弃这个服务了，是在是接入文档不理想，出问题无解。

**Comment by denghongcai** [comment]
> 这个问题是 nameSrv 给出的 broker 地址是阿里云内网的 IP，而不是 “公网IP”，是网络不通。你可以开一台 ECS 试下。ali-ons 本身就是基于开源 RocketMQ 来开发的。

说了这个 nameSrv 给出的 broker 的地址就是阿里云内网的 ip……

**Comment by zhb127** [comment]
> > 这个问题是 nameSrv 给出的 broker 地址是阿里云内网的 IP，而不是 “公网IP”，是网络不通。你可以开一台 ECS 试下。ali-ons 本身就是基于开源 RocketMQ 来开发的。
> 
> 说了这个 nameSrv 给出的 broker 的地址就是阿里云内网的 ip……

@denghongcai @gxcsoccer 也说公网环境你们测试可以，所以，我把我的环境贴出来给你们确认啊，我知道你说的是用阿里云 ECS 测试才可以。但是我们开发人员做测试的时候，难道都得购买一台 ECS 来这样测试么。我从头到尾的测试，是按照 https://help.aliyun.com/document_detail/34411.html 这个文档给的说明，说在公网地区开通，就可以公网访问。你们的 example 里面的地址，又完全跟阿里云控制台给得不一样，都不知道是文档错了，我写错了，只是让你们确认一下这个。

**Comment by gxcsoccer** [comment]
@zhb127 这是个开源项目，我们不代表阿里云，我们自己测试也是花钱买的阿里云服务。你给我们截几张图我们也无法定位什么问题

**Comment by gxcsoccer** [comment]
> @denghongcai @gxcsoccer 也说公网环境你们测试可以，所以，我把我的环境贴出来给你们确认啊，我知道你说的是用阿里云 ECS 测试才可以。但是我们开发人员做测试的时候，难道都得购买一台 ECS 来这样测试么。我从头到尾的测试，是按照 https://help.aliyun.com/document_detail/34411.html 这个文档给的说明，说在公网地区开通，就可以公网访问。你们的 example 里面的地址，又完全跟阿里云控制台给得不一样，都不知道是文档错了，我写错了，只是让你们确认一下这个。

这个问题，你可以 telnet 一下阿里云提供的公网接入点，如果 telnet 不上，那么你们可以提工单询问阿里云客服

**Comment by zhb127** [comment]
了解了，感谢。一直以为是阿里云官方 SDK。我再去找阿里云客服确认这些问题哈。

**Comment by liuhuanhui** [comment]
同样问题 请问解决没

**Comment by zhb127** [comment]
> 同样问题 请问解决没

此 SDK 的文档跟阿里云服务提供的配置，完全对应不上，后面是看源码尝试了一下，放弃使用了。

**Comment by liuhuanhui** [comment]
> > 同样问题 请问解决没
> 
> 此 SDK 的文档跟阿里云服务提供的配置，完全对应不上，后面是看源码尝试了一下，放弃使用了。

已经解决了

**Comment by zhb127** [comment]
> > > 同样问题 请问解决没
> > 
> > 
> > 此 SDK 的文档跟阿里云服务提供的配置，完全对应不上，后面是看源码尝试了一下，放弃使用了。
> 
> 已经解决了

👍

**Comment by boy461205160** [comment]
@liuhuanhui 请问如何解决的，方便讲一下么，谢谢！
