### ISSUE TITLE
how to connect to apache Rocketmq 4.x?

### ISSUE THREAD

**Issue by yarhoo** [ali-sdk/ali-ons#92]
I got error log when connect to apache rq 4.4 . Dose ali-one support it ?

            com.aliyun.openservices.ons.api.exception.ONSClientException: Connect broker failed, Topic=DevStatus, msgId=null
See http://docs.aliyun.com/cn#/pub/ons/faq/exceptions&connect_broker_failed for further details.

	at com.aliyun.openservices.ons.api.impl.rocketmq.ProducerImpl.checkProducerException(ProducerImpl.java:213)
	at com.aliyun.openservices.ons.api.impl.rocketmq.ProducerImpl.send(ProducerImpl.java:136)
	at com.aliyun.openservices.ons.api.bean.ProducerBean.send(ProducerBean.java:58)

**Comment by yarhoo** [comment]
this case by  auto obtain wrong IP . So Close it;
